### ISSUE TITLE
sxr 0.2.6 in sbt 0.7.4 project with Scala 2.8.0 throws NullPointerException in "console" action.

### ISSUE THREAD

**Issue by ghost** [harrah/browse#2]
Given this project definition:

class SHanseiProject(info : ProjectInfo) extends DefaultProject(info) with AutoCompilerPlugins
{
  val sxr = compilerPlugin("org.scala-tools.sxr" %% "sxr" % "0.2.6")
  val continuations = compilerPlugin("org.scala-lang.plugins" % "continuations" % "2.8.0")
  override def compileOptions = CompileOption("-P:continuations:enable") :: CompileOption("-P:sxr:base-directory:" + mainScalaSourcePath.asFile.getAbsolutePath) :: super.compileOptions.toList

  val specs = "org.scala-tools.testing" %% "specs" % "1.6.5" % "test"
  val scalacheck = "org.scala-tools.testing" %% "scalacheck" % "1.7" % "test"
}

"console" results in:

scala> import scala.util.continuation._
java.lang.NullPointerException
    at sxr.Browse.sxr$Browse$$getSourceFile(Browse.scala:79)
    at sxr.Browse$$anonfun$1.apply(Browse.scala:54)
    at sxr.Browse$$anonfun$1.apply(Browse.scala:54)
    at scala.collection.Iterator$$anon$19.next(Iterator.scala:369)
    at scala.collection.Iterator$$anon$19.next(Iterator.scala:369)
    at scala.collection.Iterator$class.foreach(Iterator.scala:631)
    at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:367)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:399)
    at scala.collection.Iterator$$anon$19.toList(Iterator.scala:367)
    at sxr.Browse.generateOutput(Browse.scala:57)
    at sxr.BrowsePlugin$BrowsePhase.run(BrowsePlugin.scala:107)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:733)
    at scala.tools.nsc.Interpreter.scala$tools$nsc$Interpreter$$_initialize(Interpreter.scala:117)
    at scala.tools.nsc.Interpreter$$anonfun$initialize$1.apply$mcZ$sp(Interpreter.scala:137)
    at scala.tools.nsc.Interpreter$$anonfun$initialize$2.apply(Interpreter.scala:137)
    at scala.tools.nsc.Interpreter$$anonfun$initialize$2.apply(Interpreter.scala:137)
    at scala.concurrent.ThreadRunner$$anon$2$$anonfun$run$2.apply(ThreadRunner.scala:45)
    at scala.concurrent.ThreadRunner.scala$concurrent$ThreadRunner$$tryCatch(ThreadRunner.scala:31)
    at scala.concurrent.ThreadRunner$$anon$2.run(ThreadRunner.scala:45)
    at java.lang.Thread.run(Thread.java:613)

**Comment by harrah** [comment]
Yes, sxr should ignore compilation units without a corresponding source file.  You can disable it by overriding consoleOptions (I think this is in sbt 0.7.4)

**Comment by harrah** [comment]
Fixed by Olivier in http://github.com/harrah/browse/commit/a5c258b1626457648d1ef36faaac1ed7e6c0e84f.
